apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-backend-ingress
  namespace: chatbot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev-issuer
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: dome-gpt.dome-marketplace-sbx.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatbot-backend
            port:
              number: 5000
  tls:
  - hosts:
    - dome-gpt.dome-marketplace-sbx.org
    secretName: chatbot-backend-tls-secret