orion:
  deployment:
    additionalAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '8000'
    image: 
      tag: 1.1.0
  broker:
    logging:
      level: DEBUG
    db:
      auth: 
        user: root
        mech: "SCRAM-SHA-1"
      hosts:
        - mongodb-trust
      user: root
      existingSecret:
        name: mongodb-secret
        key: mongodb-root-password
  mongo:
    # we want to use the individually deployed mongodb
    enabled: false
  initData:
    initEnabled: true
    hook: post-install, post-upgrade
    entities:
      - name: "onboarding.dome-marketplace-sbx.org"
        data: |
          {
            "@context": "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
            "id": "urn:ngsi-ld:TrustedIssuer:did:web:onboarding.dome-marketplace-sbx.org",
            "type": "TrustedIssuer",
            "issuer": {
                "type": "Property",
                "value": "did:web:onboarding.dome-marketplace-sbx.org"
            },
            "selfDescription": {
                "type": "Property",
                "value": {
                    "id": "did:web:onboarding.dome-marketplace-sbx.org",
                    "type": "gx:LegalParticipant",
                    "gx:legalName": "Marketplcae Onboarding Service"
                }
            }
          }