trusted-issuers-registry:
  replicaCount: 1
  deployment:
    image:
      tag: 0.7.2
      pullPolicy: Always
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-aws-prod
    className: nginx
    hosts: 
      - host: tir.dome-marketplace.org
        paths:
          - "/"
    tls: 
      - hosts: 
        - tir.dome-marketplace.org
        secretName: trusted-issuers-registry-tls-sec

  additionalEnvVars:
    - name: SATELLITE_KEY
      valueFrom:
        secretKeyRef:
          name: satellite-key-secret
          key: private-key
  tir:
    ngsiBroker:
      url: http://orion-ld-trust:1026/
    contextUrl: "https://registry.lab.dsba.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
    satellite:
      id: "EU.EORI.FIWARESATELLITE"
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIGhjCCBG6gAwIBAgIUUliLPK6R7OeviNDRY2dtI/G7YQIwDQYJKoZIhvcNAQEL
        BQAwgYwxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCZXJsaW4xHzAdBgNVBAoMFkZp
        d2FyZSBGb3VuZGF0aW9uIGUuVi4xCzAJBgNVBAsMAklUMRwwGgYDVQQDDBNGSVdB
        UkVfSU5URVJNRURJQVRFMSAwHgYJKoZIhvcNAQkBFhFmaXdhcmVAZml3YXJlLm9y
        ZzAeFw0yMjExMDkwNzU0MjBaFw0yNzExMDgwNzU0MjBaMIGkMQswCQYDVQQGEwJE
        RTEPMA0GA1UECAwGQmVybGluMQ8wDQYDVQQHDAZCZXJsaW4xEjAQBgNVBAoMCVNh
        dGVsbGl0ZTEYMBYGA1UEAwwPRklXQVJFU0FURUxMSVRFMSMwIQYJKoZIhvcNAQkB
        FhRzYXRlbGxpdGVAZml3YXJlLm9yZzEgMB4GA1UEBRMXRVUuRU9SSS5GSVdBUkVT
        QVRFTExJVEUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC8SfhOKnws
        CpcxcGXzofaf5Oa1VASXDqv21lQQtWs9KBzoSJYDJ4DzH6MLIVbsNrTeugyF7D2y
        bgzqqQ19igeNj7PZYmbwlzQ/B9eQaRpAwjdNF4h1cQpXVCLSLa9/WwtxV6hTdTs/
        9er3tCiGi1fCe1Hggl/ykEC4OxYq3CAzmnfI7TwmI721oLdPXkbyM46IHbQOry/d
        KFXjjaf3yur46k9NfEc3Ed3W4vqdILVF1gjFUiY8EQVTNcR3RBXiaQgHyEcbfPcz
        lQOK67EyaA+mJ1gw0A5FFqeGFzu6vCPX/SfHUzHv0jAgyig2QOdMy5AD1EDs1F1D
        N0QRCSo4TIIrz97tA0Ou+F5qVu9JqYjeS9/Aobds9O/tRjAyg6tqVE0Th9Kyyxw9
        CJ3m1316JNpu4AIIJBHaEE/Eo9FZ/JZ/XrFn0SwdJogKtGX+ACuMtsIsuzQfhV4q
        cHZKWBG+btWFekqJQEk0A1uMV8Khoyg08hoo1Q+p1uPix2E0X6UAYDhGgdDxGxnD
        EZgBL4yQgjoWzDe/rAPBjvlchdPH9QUgUsxlVa8yiNuyx8pZb40yKRCSL4I5OWLk
        37/sYqxsljpobhJl390YE35LfhmqKZShVMnNDexQQ92o+LD7MPLhSrVqL0o/DDIl
        zuOdynlnyp5rAzDiBr/+BwDqYXhEv5fGZQIDAQABo4HFMIHCMAkGA1UdEwQCMAAw
        EQYJYIZIAYb4QgEBBAQDAgWgMDMGCWCGSAGG+EIBDQQmFiRPcGVuU1NMIEdlbmVy
        YXRlZCBDbGllbnQgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFBwGLZR583u1g+bTzyl9
        lQsDLoa5MB8GA1UdIwQYMBaAFCdVXai4piVrVEDg/6LNuF4f0o0OMA4GA1UdDwEB
        /wQEAwIF4DAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwDQYJKoZIhvcN
        AQELBQADggIBAH9QGWANJEikCdoUAprRTbap2Yr44KUks3df/BawYnvWfTxBfhNZ
        5k9Fln5uGoOKb7MYmBAQ0ZuooPrb6srPZOEORdluxxbCgp9PoukOvLmHype13msA
        0yIvBuDLgPj5HesJ2dSdTwOThisZAov3B6+gt4MMt+4WPD24cfbB7sUgJWnTaKzC
        jivLdt+j/ymZFl41tb5kGcKv3OmYYTiy5V5DMxataZargN71mM0QElxR6kKWgkgK
        6slcvwMHOyn+o/DezgoUkdtA7gwa9sFnwHoxbId427BQd0BdtEVMyiQqutYquQbQ
        wwbB6K5+7rcpdsFRl7OzQmmll6SGKcjmm1stZANlZj41lWKg5IG0Xw+8Ei3lHL62
        imVFD1YgPuAAOcCkLpvnoAtcWvMInAhUMev8XukgrBO4tdyB8qteQelRLYYvWOf5
        gzscb/B2g18g4KtSM6IGd8/QzsU9dJE2e0VcXTgkIJgRVIX5VJy53YxHEsKOWqm7
        /t2baJSFLhS3aDmcC+BUtnQcOQzMTy+Idb96sU/pUdJCmJBlJ6g4Kg4zsZAiFbou
        ZUkzFO9WH+elKhqHZRw6MFFZ4Srb8JSpkCh7DP/H5XDKOCsGtgZKCHd1bC29mcer
        lYGR6nNL82ub8PwlYAom7eVFiwLpZwKp/hQoAtDF84bCNOwhQbIw3HTq
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIGAjCCA+qgAwIBAgIBATANBgkqhkiG9w0BAQsFADCBkzELMAkGA1UEBhMCREUx
        DzANBgNVBAgMBkJlcmxpbjEPMA0GA1UEBwwGQmVybGluMR8wHQYDVQQKDBZGaXdh
        cmUgRm91bmRhdGlvbiBlLlYuMQswCQYDVQQLDAJJVDESMBAGA1UEAwwJRklXQVJF
        X0NBMSAwHgYJKoZIhvcNAQkBFhFmaXdhcmVAZml3YXJlLm9yZzAeFw0yMjExMDkw
        NzM5MzdaFw0zMDAyMTAwNzM5MzdaMIGMMQswCQYDVQQGEwJERTEPMA0GA1UECAwG
        QmVybGluMR8wHQYDVQQKDBZGaXdhcmUgRm91bmRhdGlvbiBlLlYuMQswCQYDVQQL
        DAJJVDEcMBoGA1UEAwwTRklXQVJFX0lOVEVSTUVESUFURTEgMB4GCSqGSIb3DQEJ
        ARYRZml3YXJlQGZpd2FyZS5vcmcwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
        AoICAQDFawfVVoUqE/HYcgHNPjjK4xHA5ClWIx4lvXskCshK95KnePdkOSK8Lhp5
        sQB/K0A6bU9IA7LeNhloTQ1u+pn0H/ml0XAH+1QVmDURxy50mC0FKp4scMVsW6Ps
        21A2QaRYADZj9BjFt7UeuCWAtDXupuEw/+SPLnDByfY3nEnhOWerNfdXiAhp2STY
        pOa1A/OTARLWz/wJSrTynC7sWcE/QCW5YuK+kOH1KyUlFY/NLY+7n9E6rHte2hjG
        Sgie4EH7xps2VLcmJhKe5sUXWcmoPnIY42iNgMFcYy0xQT9oWY4fohL9Qy6yB30p
        yKFuuejF39ntB6VMJ0Jozg816CigJoP9yjNmNSLhNGCp9sqD83qnV5nIJtoQijCZ
        j15vYLdKvG7iM9jkOP09V9kY6QUWBeFTuHe0n77D4FMey6rC1GHeNXTwSOretbD9
        zl9Tx9BNPRsX9MNKoXif2sT2eKA0IJs2gUAPCncVORMax6YuXkdZKByhRitNl33p
        LLATANzdg2YgHwBeggY1HfFYDVc++t1cZUitHTKXeQ5YW+b2Rs+5+d/aNA8pAipG
        ZoML9GoE2lDPTFegjXn4vDg7FaVFIy6G1D6TWSmb6WJ6b+zAk3Gflc3wuYXtpI5Y
        x6ynpd++OZ7oVCcKmu7aSfE+K2kefd0MaIM28meu0qQ10j447QIDAQABo2YwZDAd
        BgNVHQ4EFgQUJ1VdqLimJWtUQOD/os24Xh/SjQ4wHwYDVR0jBBgwFoAUWcEwA+U0
        c5pQNn+5hlX5EhaiZCcwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMC
        AYYwDQYJKoZIhvcNAQELBQADggIBAETCN8uSZ+C7eTs4SsscUTivlw+eI6Zi7lvP
        AjRkHLSpCSkgtH5Ep+QtXLjj1li4OyLL81G6VvJqektr0CCk94AkxLy4DZHAWBtA
        vL0k8UYHvdhSZUBWhMcRum51g8yvVFIJCKPfOCsfzbjGKdOkv4T5RKBrAcFIFCvL
        dBl1j7dHRARtCy+Gyup4oPqlult5COtvTJJ7Yvd6Mmqg8TbDvD4C5vh7k6wT/ar+
        rlWiMJ8VG8CpEJD/7MGWP3woHRf6WUNLxj5VRsS+4O6b5cXsrrxog1YkkRN6ZDuH
        G8NdsdufE2JzK2wOlfxhGsgRIVheQqS3kgxXEpeFB8FXJKt57e+RD3fnqh8UA+ng
        3ghIanWL7kPI0/jQc8yxoZxAZ8pjiTuoU2JO7/eYHALJ/GFkDTkyDDKY2cbiVEFP
        FYM6lL3OV7dV99BRGclv2niuo2FfL/XTkUJPCeAnI7n9NgOKY+VXD5yEfAsLVqZm
        AAnJqYcdqN3WANfn30Q6wRiaimLSwRMY8g4DXsFy8xMiZcf4tKpLg/Ip/mUuMNZB
        tKpDMSCikMoQiuu1+AkkGtWImwvS3JnXipEA6ZuABYTHzIGEcc76T3sg9KIgZVKR
        a510g7F8CAaaAUkqXPpmWC0SXjZ50srIiFinaE8x45BElmWCHlcIT9gKzkatqbVO
        jDOUKVLp
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIGCTCCA/GgAwIBAgIUE4eZnRRqaub9kC+3PqDYNfVU8IcwDQYJKoZIhvcNAQEL
        BQAwgZMxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCZXJsaW4xDzANBgNVBAcMBkJl
        cmxpbjEfMB0GA1UECgwWRml3YXJlIEZvdW5kYXRpb24gZS5WLjELMAkGA1UECwwC
        SVQxEjAQBgNVBAMMCUZJV0FSRV9DQTEgMB4GCSqGSIb3DQEJARYRZml3YXJlQGZp
        d2FyZS5vcmcwHhcNMjIxMTA5MDcyNDU2WhcNMzIxMTA2MDcyNDU2WjCBkzELMAkG
        A1UEBhMCREUxDzANBgNVBAgMBkJlcmxpbjEPMA0GA1UEBwwGQmVybGluMR8wHQYD
        VQQKDBZGaXdhcmUgRm91bmRhdGlvbiBlLlYuMQswCQYDVQQLDAJJVDESMBAGA1UE
        AwwJRklXQVJFX0NBMSAwHgYJKoZIhvcNAQkBFhFmaXdhcmVAZml3YXJlLm9yZzCC
        AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOoPnXAtWFG6Bsdr4TvBUW12
        wpcRYH9fiDm5Mc6g6VdiL9I1tWMbhfO7DPyOaoqh6xloDL+XoeREmoIfJJpY3bdu
        zPswTinaMd7H+aMP6wWDsAIABhmw5Pui3UbpUZeFeo3RMe5f8JjL4KPgjWCX1llx
        O6yxy1e8gSfGpBkEHpJc8lKQwDE9zgyuiOLRUPRtSe0NJajcBrrXiaSPGdXvG39N
        YzjAARo5PAEBG+UHHzZFeS11MT+GbryZrx9KbdmVshdlsGqL/2sTY9veFrz53XLR
        Gmq86U+IQZEEvp6Z5k5ZwamBiACiRDbSwh1Ngp+BKNG26wCvB4gfxTOuSHIfzRkP
        D8vdV7mZwyeFHXogsNqF/8Pmdy0ONcqThh7w7lUFMVygk9q531n6QGRRpwCgKAjy
        jYN5r2Mo68+tmxNCejIPpo/JsAEKlPsh9lH7KhSEjIaHx//Q2f/nll1Z4GkXj7Sk
        ALz3P4ljT3ePeT2wnlSpyrCEPIeMXT47Z2xdc9MgXhqxidep7sUWFMaJwKhq1m1U
        JXI216GKUN3y//WSvRu7tqzyuUR9qsfY946EUF6m4XQjj9wke6H7vTpY9U/zwc9j
        yx+fXnJiuYht6k2cHav9GK0wnZ5Ct6A1+43eRR43EJ11OM9Ml+J4tdfukSrW6ppm
        z+4Yxfe5RRtzPeXxncjbAgMBAAGjUzBRMB0GA1UdDgQWBBRZwTAD5TRzmlA2f7mG
        VfkSFqJkJzAfBgNVHSMEGDAWgBRZwTAD5TRzmlA2f7mGVfkSFqJkJzAPBgNVHRMB
        Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQDGFxElC2Sq6/EOcbzQ7tjaqc5d
        v2FCWTTQYQLiS+VQqcJqGnMnEwWUDCeacQ6BaxdTW+jb1zX66DgfNJ40Yr2YDVv4
        qr+KKCW+q8cKQUte/XmcpLJtrXtYZQMeLUfwBlF2yAvmb3/2cda0VIhsem2BIFCE
        227+wOYqHSqpkqfVcizljnYLTwvTBQz5P0Jq9/wPcjB7fxfko2mZjaPQFfEuLPMT
        Jttv7711TJCrp0gzmnICS1Ba3vtcdZN+rd6IoSQmudnOcGDJkslL77T4BzjXDkax
        fuCoQ6f/hwXJuJF3fQHd6OsJHDgVAJQ78Nyb5P/2KMpdY/nkudeBG3ZcEJP7uptc
        QnWmMMLbfuGuXmAvXyKJJ3bw01F9+Vfo5OLud4IVnv0QDlXLHBDdGErBTT6m5XZN
        SyBXbqp1xIui+Jufm4HY0Y7kX0QzfSHdMXWgiIdmR8z0x15PQg/uFihXjp/RyqDr
        G+Tin3TXBqJRdDxYCwdnoutQnqtYCbsidoLv2ZA0vQiGfykPMpU49dGKwVCZBw1y
        Lf8X0QG5Vxp9O42jXzSy5rYwrF76FTpy+h7UqmZNOBXJG1roKrQWZ2OieFMp/rTD
        YURyhqWqqW2u7UehYs6emmSwYv8j0v4CzpH517jp2RJNyinI3TZmgD0AAKzyJAl/
        Zqat8t/baTS3TUdIKg==
        -----END CERTIFICATE-----

      trustedList:
        - name: LETS_ENCRYPT_CA
          crt: |
            -----BEGIN CERTIFICATE-----
            MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
            MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
            DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
            TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
            cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
            AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
            ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
            wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
            LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
            4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
            bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
            sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
            Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
            FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
            SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
            PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
            TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
            SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
            c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
            +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
            ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
            b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
            U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
            MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
            5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
            9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
            WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
            he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
            Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
            -----END CERTIFICATE-----
        - name: FIWARE_CA
          crt: |
            -----BEGIN CERTIFICATE-----
            MIIGCTCCA/GgAwIBAgIUE4eZnRRqaub9kC+3PqDYNfVU8IcwDQYJKoZIhvcNAQEL
            BQAwgZMxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCZXJsaW4xDzANBgNVBAcMBkJl
            cmxpbjEfMB0GA1UECgwWRml3YXJlIEZvdW5kYXRpb24gZS5WLjELMAkGA1UECwwC
            SVQxEjAQBgNVBAMMCUZJV0FSRV9DQTEgMB4GCSqGSIb3DQEJARYRZml3YXJlQGZp
            d2FyZS5vcmcwHhcNMjIxMTA5MDcyNDU2WhcNMzIxMTA2MDcyNDU2WjCBkzELMAkG
            A1UEBhMCREUxDzANBgNVBAgMBkJlcmxpbjEPMA0GA1UEBwwGQmVybGluMR8wHQYD
            VQQKDBZGaXdhcmUgRm91bmRhdGlvbiBlLlYuMQswCQYDVQQLDAJJVDESMBAGA1UE
            AwwJRklXQVJFX0NBMSAwHgYJKoZIhvcNAQkBFhFmaXdhcmVAZml3YXJlLm9yZzCC
            AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOoPnXAtWFG6Bsdr4TvBUW12
            wpcRYH9fiDm5Mc6g6VdiL9I1tWMbhfO7DPyOaoqh6xloDL+XoeREmoIfJJpY3bdu
            zPswTinaMd7H+aMP6wWDsAIABhmw5Pui3UbpUZeFeo3RMe5f8JjL4KPgjWCX1llx
            O6yxy1e8gSfGpBkEHpJc8lKQwDE9zgyuiOLRUPRtSe0NJajcBrrXiaSPGdXvG39N
            YzjAARo5PAEBG+UHHzZFeS11MT+GbryZrx9KbdmVshdlsGqL/2sTY9veFrz53XLR
            Gmq86U+IQZEEvp6Z5k5ZwamBiACiRDbSwh1Ngp+BKNG26wCvB4gfxTOuSHIfzRkP
            D8vdV7mZwyeFHXogsNqF/8Pmdy0ONcqThh7w7lUFMVygk9q531n6QGRRpwCgKAjy
            jYN5r2Mo68+tmxNCejIPpo/JsAEKlPsh9lH7KhSEjIaHx//Q2f/nll1Z4GkXj7Sk
            ALz3P4ljT3ePeT2wnlSpyrCEPIeMXT47Z2xdc9MgXhqxidep7sUWFMaJwKhq1m1U
            JXI216GKUN3y//WSvRu7tqzyuUR9qsfY946EUF6m4XQjj9wke6H7vTpY9U/zwc9j
            yx+fXnJiuYht6k2cHav9GK0wnZ5Ct6A1+43eRR43EJ11OM9Ml+J4tdfukSrW6ppm
            z+4Yxfe5RRtzPeXxncjbAgMBAAGjUzBRMB0GA1UdDgQWBBRZwTAD5TRzmlA2f7mG
            VfkSFqJkJzAfBgNVHSMEGDAWgBRZwTAD5TRzmlA2f7mGVfkSFqJkJzAPBgNVHRMB
            Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQDGFxElC2Sq6/EOcbzQ7tjaqc5d
            v2FCWTTQYQLiS+VQqcJqGnMnEwWUDCeacQ6BaxdTW+jb1zX66DgfNJ40Yr2YDVv4
            qr+KKCW+q8cKQUte/XmcpLJtrXtYZQMeLUfwBlF2yAvmb3/2cda0VIhsem2BIFCE
            227+wOYqHSqpkqfVcizljnYLTwvTBQz5P0Jq9/wPcjB7fxfko2mZjaPQFfEuLPMT
            Jttv7711TJCrp0gzmnICS1Ba3vtcdZN+rd6IoSQmudnOcGDJkslL77T4BzjXDkax
            fuCoQ6f/hwXJuJF3fQHd6OsJHDgVAJQ78Nyb5P/2KMpdY/nkudeBG3ZcEJP7uptc
            QnWmMMLbfuGuXmAvXyKJJ3bw01F9+Vfo5OLud4IVnv0QDlXLHBDdGErBTT6m5XZN
            SyBXbqp1xIui+Jufm4HY0Y7kX0QzfSHdMXWgiIdmR8z0x15PQg/uFihXjp/RyqDr
            G+Tin3TXBqJRdDxYCwdnoutQnqtYCbsidoLv2ZA0vQiGfykPMpU49dGKwVCZBw1y
            Lf8X0QG5Vxp9O42jXzSy5rYwrF76FTpy+h7UqmZNOBXJG1roKrQWZ2OieFMp/rTD
            YURyhqWqqW2u7UehYs6emmSwYv8j0v4CzpH517jp2RJNyinI3TZmgD0AAKzyJAl/
            Zqat8t/baTS3TUdIKg==
            -----END CERTIFICATE-----
    additionalConfigs:
      logger:
        levels:
          ROOT: ERROR
          org.fiware.iam: DEBUG
