apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: knowledgebase
  labels:
    app.kubernetes.io/instance: bookstack
    app.kubernetes.io/name: bookstack
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: bookstack
      app.kubernetes.io/name: bookstack
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bookstack
        app.kubernetes.io/name: bookstack
    spec:
      containers:
        - name: bookstack
          image: sh3rd3n/dome-bookstack:1.0.0
          env:
            - name: DB_HOST
              value: "mysql-knowledgebase:3306"
            - name: DB_DATABASE
              value: "bookstack"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstack-secret
                  key: DB_PASSWORD
            - name: APP_URL
              value: "https://knowledgebase.dome-marketplace-sbx.org"
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: bookstack-secret
                  key: APP_KEY
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bookstack-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstack-secret
                  key: MAIL_PASSWORD
            - name: MAIL_HOST
              value: "sandbox.smtp.mailtrap.io"
            - name: MAIL_PORT
              value: "2525"

            - name: AUTH_METHOD
              value: "oidc"
            - name: AUTH_AUTO_INITIATE
              value: "true"
            - name: OIDC_NAME
              value: "DOME SSO"
            - name: OIDC_DISPLAY_NAME_CLAIMS
              value: "name"
            - name: OIDC_CLIENT_ID
              value: "bookstack"
            - name: OIDC_CLIENT_SECRET
              value: "N1e9syMGGDsnjlxTsLKwaB0OrrG17b51"
            - name: OIDC_ISSUER
              value: "https://cs-identity.dome-marketplace-sbx.org/realms/dome"
            - name: OIDC_END_SESSION_ENDPOINT
              value: "https://cs-identity.dome-marketplace-sbx.org/realms/dome/protocol/openid-connect/logout"
            - name: OIDC_ISSUER_DISCOVER
              value: "true"
            - name: OIDC_USER_TO_GROUPS
              value: "true"
            - name: OIDC_GROUPS_CLAIM
              value: "groups"
            - name: OIDC_ADDITIONAL_SCOPES
              value: "groups"
            - name: OIDC_REMOVE_FROM_GROUPS
              value: "true"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/bookstack/public/uploads
              name: bookstack-uploads
            - mountPath: /var/www/bookstack/storage/uploads
              name: bookstack-storage-uploads
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      volumes: 
      - name: bookstack-uploads
        persistentVolumeClaim:
          claimName: kb-bookstack-uploads-pvc
      - name: bookstack-storage-uploads
        persistentVolumeClaim:
          claimName: kb-bookstack-storage-uploads-pvc