logLevel: debug

expose:
 type: nodePort
 tls:
   enabled: false

# Persistencia para componentes
persistence:
 enabled: true
 resourcePolicy: "keep"
 persistentVolumeClaim:
   registry:
     size: 40Gi
   jobservice:
     size: 1Gi
   database:
     size: 1Gi
   redis:
     size: 1Gi
   trivy:
     size: 5Gi

# Base de datos externa
database:
 type: external
 external:
   host: pg-75qkrjg6i4d7tlg2.postgresql.de-txl.ionos.com
   port: 5432
   username: harboruser
   coreDatabase: harbordb
   existingSecret: harbor-db-secret
   existingSecretPasswordKey: password
   sslmode: require

redis:
 type: internal

trivy:
 enabled: true

chartmesum:
 enabled: true

core:
 replicaCount: 1

jobservice:
 replicaCount: 1

registry:
 replicaCount: 1