apiVersion: v1
kind: ConfigMap
metadata:
  name: certification-backend-config
  namespace: dome-certification
data:
  POSTGRES_DB: dome
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_URL: jdbc:postgresql://dekra-postgres:5432/dome
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_MVC_CONVERTERS_PREFERRED_JSON_MAPPER: jackson
  FILE_UPLOAD_DIR: /dome-upload
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
  SPRINGDOC_API_DOCS_PATH: /api-docs
  SPRINGDOC_SWAGGER_UI_PATH: /api-docs.html
  # LOGGING_FILE_NAME: dome-certification.log
  # LOGGING_LEVEL_ROOT: INFO
  SPRING_MAIL_USERNAME: certification@dome-marketplace.eu
  SPRING_MAIL_ADDRESS: certification@dome-marketplace.eu
  SPRING_MAIL_HOST: smtp.ionos.de
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_SMPT_AUTH: "true"
  SPRING_MAIL_SMPT_START_TLS_ENABLE: "true"
  SPRING_MAIL_SMPT_START_TLS_REQUIRED: "true"
  SPRING_MAIL_SMPT_SSL_TRUST: smtp.ionos.de
  SPRING_MAIL_SMPT_DEBUG: "false"
  JWT_PUBLIC_KEY_X: X-tT8nBVVvEwTnD0dOsFEMe0xTogvSFF21crzcezGyw
  JWT_PUBLIC_KEY_Y: 2ewVHc6-KbG3xNkogzA5okub-A87ecgi3o2k2Tg7kaM
  JWT_OAUTH_CLIENT_ID: did:key:zDnaep7iGodkmSEUD8uAsp4dhqcaxxrFQ3zgyANHD2brt7CgB
  JWT_OAUTH_REDIRECT_URI: https://dome-certification.dome-marketplace-sbx.org/auth/login
  JWT_OAUTH_AUD: https://verifier.dome-marketplace-sbx.org
  JWT_ISSUER_URL: https://issuer.dome-marketplace-sbx.org
