business-api-ecosystem:
  bizEcosystemApis:
    # Revert paths to empty strings.
    fullnameOverride: tmforum-api-proxy
    enabled: false

    tmForum:
      catalog:
        host: tm-forum-api-product-catalog
        port: 8080
        path: /tmf-api/productCatalogManagement/v4
      inventory:
        host: tm-forum-api-product-inventory
        port: 8080
        path: /tmf-api/productInventory/v4
      ordering:
        host: tm-forum-api-product-ordering-management
        port: 8080
        path: /tmf-api/productOrderingManagement/v4
      billing:
        host: tm-forum-api-account
        port: 8080
        path: /tmf-api/accountManagement/v4
      usage:
        host: tm-forum-api-usage-management
        port: 8080
        path: /tmf-api/usageManagement/v4
      party:
        host: tm-forum-api-party-catalog
        port: 8080
        path: /tmf-api/party/v4
      customer:
        host: tm-forum-api-customer-management
        port: 8080
        path: /tmf-api/customerManagement/v4
      resources:
        host: tm-forum-api-resource-catalog
        port: 8080
        path: /tmf-api/resourceCatalog/v4
      services:
        host: tm-forum-api-service-catalog
        port: 8080
        path: /tmf-api/serviceCatalogManagement/v4
      resourceInventory:
        host: tm-forum-api-resource-inventory
        port: 8080
        path: /tmf-api/serviceInventory/v4

  bizEcosystemRss:
    enabled: false

  siop:
    enabled: true
    clientId: did:key:zDnaeypyWjzn54GuUP7PmDXiiggCyiG7ksMF7Unm7kjtEKBez
    verifier:
      host: https://verifier.dome-marketplace-sbx.org
      qrCodePath: /oidc/authorize
      tokenPath: /oidc/token
      jwksPath: /oidc/jwks
    allowedRoles:
      - seller
      - customer
      - admin
    # Configuration for the Credential Config Service initiation
    ccs:
      endpoint: "http://credentials-config-service:8080"
      defaultOidcScope: "defaultScope"
      # -- Credential configurations for particular scopes
      oidcScopes:
        didRead: 
          - type: "VerifiableCredential"
            trustedParticipantsLists: [
              "http://trusted-issuers-list:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list:8080"
            ]
          - type: "LegalPersonCredential"
            trustedParticipantsLists: [
              "http://trusted-issuers-list:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list:8080"
            ]
          - type: "LEARCredentialEmployee"
            trustedParticipantsLists: [
              "http://trusted-issuers-list:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list:8080"
            ]
        defaultScope:
          - type: "VerifiableCredential"
            trustedParticipantsLists: [
              "http://trusted-issuers-list:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list:8080"
            ]
          - type: "LegalPersonCredential"
            trustedParticipantsLists: [
              "http://trusted-issuers-list:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list:8080"
            ]
          - type: "LEARCredentialEmployee"
            trustedParticipantsLists: [
              "http://trusted-issuers-list:8080"
            ]
            trustedIssuersLists: [
              "http://trusted-issuers-list:8080"
            ]

  externalUrl: https://dome-marketplace-sbx.org

  bizEcosystemChargingBackend:

    maxUploadSize: "5242880"

    serviceAccount:
      create: true

    deployment:
      image:
        repository: fiware/biz-ecosystem-charging-backend
        tag: "10.1.0"
        pullPolicy: Always
    
    plugins:
      enabled: true
      annotations:
        helm.sh/resource-policy: "keep"

    media:
      enabled: true
    
    port: 8006

    loglevel: debug

    payment:
      method: dpas

    existingSecret: bae-secret
    db: 
      host: mongodb
      database: charging_db
      user: charging
    
    backup:
      enabled: false

    initContainers: false
    propagateToken: true
    basePath: /opt/business-ecosystem-charging-backend
    token: 
      enabled: false

    extraEnvVars:
      - name: BAE_CB_CUSTOMER_BILL
        value: "http://tm-forum-api-customer-bill-management:8080/tmf-api/customerBill/v4"
      - name: BAE_CB_DPAS_CLIENT_API_URL
        value: "https://dpas-sbx.egroup.hu/api/payment-start"
      - name: BAE_CB_PARTY
        value: "http://tm-forum-api-party-catalog:8080/tmf-api/party/v4"

  oauth:
    provider: "vc"

  bizEcosystemLogicProxy:

    serviceAccount:
      create: true
    
    existingSecret: bae-secret

    statefulset:
      image:
        repository: fiware/biz-ecosystem-logic-proxy
        tag: "10.2.0-PRE-3"
        pullPolicy: Always

    ingress: 
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-sbx-issuer
      tls: 
       -  hosts: 
            - dome-marketplace-sbx.org
          secretName: walt-id-vcwaltid-tls-sec
      hosts: 
        - host: dome-marketplace-sbx.org
          paths: 
            - "/"

    port: 8004
    nodeEnvironment: production

    db:
      host: mongodb
      database: belp_db
      user: belp
    basePath: /opt/business-ecosystem-logic-proxy

    externalIdp:
      enabled: true
    initContainers: false
    propagateToken: true
    additionalEnvVars:
      - name: MIGRATE_DATA
        value: "False"
      - name: BAE_LP_SIOP_IS_REDIRECTION
        value: "true"
      - name: BAE_LP_CHAT_URL
        value: https://eng-gpt.dome-marketplace-sbx.org/predict
      - name: BAE_LP_KNOWLEDGE_BASE_URL
        value: https://knowledgebase.dome-marketplace-sbx.org/
      - name: BAE_LP_TICKETING_URL
        value: https://ticketing.dome-marketplace-sbx.org/
      - name: BAE_LP_SIOP_OPERATORS
        value: VATES-B87798617,VATIT-05724831002
      - name: BAE_LP_SEARCH_URL
        value: http://dome-search-svc.search-engine.svc.cluster.local:8080
      - name: BAE_LP_MATOMO_ID
        value: "3"
      - name: BAE_LP_MATOMO_URL
        value: https://dome-webstats.eurodyn.com/
      - name: BAE_LP_DOME_TRUST
        value: https://dome-certification.dome-marketplace-sbx.org
      - name: BAE_LP_PURCHASE_ENABLED
        value: "true"
      - name: BAE_LP_DOME_ABOUT
        value: https://dome-project.eu/about/
      - name: BAE_LP_DOME_REGISTRATION_FORM
        value: https://onboarding.dome-marketplace.eu/
      - name: BAE_LP_DOME_ONBOARDING_GUIDELINES
        value: https://knowledgebase.dome-marketplace-prd.org/books/company-onboarding-process-guide-for-cloud-service-providers-csp
      - name: BAE_LP_DOME_GUIDELINES
        value: https://knowledgebase.dome-marketplace-prd.org/books/managing-orders-products-and-subscriptions
      - name: BAE_LP_BILLING_ENGINE_URL
        value: http://bae-marketplace-biz-ecosystem-charging-backend.marketplace.svc.cluster.local:8006
      - name: BAE_LP_ENDPOINT_CUSTOMER_BILL_HOST
        value: tm-forum-api-customer-bill-management
      - name: BAE_LP_ENDPOINT_CUSTOMER_BILL_PORT
        value: "8080"
      - name: BAE_LP_SIOP_PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            name: bae-secret
            key: privateKey
