apiVersion: apps/v1
kind: Deployment
metadata:
  name: dome-search-deployment
  namespace: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dome-search
      app.kubernetes.io/name: dome-search
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dome-search
        app.kubernetes.io/name: dome-search
    spec:
      containers:
        - name: search
          image: production.eng.it:8433/dome/search:0.1.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          env:
            - name: ELASTICSEARCH_ADDRESS_HOST
              value: elasticsearch-master
            - name: ELASTICSEARCH_ADDRESS_PORT
              value: "9200"
            - name: network.host
              value: "0.0.0.0"
            - name: ELASTIC_USERNAME
              value: elastic
            - name: ELASTIC_PASSWORD
              value: dome_2024!
            - name: TMFORUM_SERVICE_CATALOG_URL
              value: http://tm-forum-api-service-catalog.marketplace.svc.cluster.local:8080
            - name: TMFORUM_PRODUCT_CATALOG_URL
              value: http://tm-forum-api-product-catalog.marketplace.svc.cluster.local:8080
            - name: TMFORUM_RESOURCE_CATALOG_URL
              value: http://tm-forum-api-resource-catalog.marketplace.svc.cluster.local:8080
            - name: BAE_URL
              value: http://bae-marketplace-biz-ecosystem-logic-proxy.marketplace.svc.cluster.local:8004
            - name: LOG_LEVEL
              value: DEBUG
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
