apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    certificate-authority-data: %CA_CRT%
    server: %SERVER_URL%
  name: %NAMESPACE%-cluster-%ENV%
users:
- name: %USER%
  user:
    token: %TOKEN%
contexts:
- context:
    cluster: %NAMESPACE%-cluster-%ENV%
    namespace: %NAMESPACE%
    user: %USER%
  name: %NAMESPACE%-%ENV%
current-context: %NAMESPACE%-%ENV%