
doc: 
  defaultApi: party-catalog
  defaultPath: /tmf-api/party/v4


tm-forum-api:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prd-issuer
    # -- host to be used
    hosts:
      - host: tmforum.dome-marketplace-prd.org
    tls:
    - hosts:
      - tmforum.dome-marketplace-prd.org
      secretName: tmforum-tls 

  apiProxy:
    image:
      tag: distroless-v1.27-latest
    enabled: false
    service: 
      nameOverride: tmforum-api-proxy


  ## configuration to be used by every api-deployment if nothing specific is provided.
  defaultConfig:
  
    # -- configuration to be used for the image of the container
    image:
      # -- repository to get the container from
      repository: quay.io/fiware
      # -- tag to be used, most of the time the apis will use the same version
      tag: 1.4.1
      # -- pull policy to be used
      pullPolicy: IfNotPresent

    # --  ngsi-ld broker connection information
    ngsiLd:
      # -- timeout for requests ot the broker
      readTimeout: 30s
      # -- base path for the ngsi-ld api
      path: ngsi-ld/v1
      # -- address of the broker
      url: http://scorpio:1026

    logLevel: INFO
    contextUrl: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld

    additionalEnvVars:
      - name: GENERAL_NGSILDORQUERYVALUE
        value: ","
      - name: GENERAL_NGSILDORQUERYKEY
        value: ","
      - name: GENERAL_ENCLOSEQUERY
        value: "false"
      - name: API_EXTENSION_ENABLED
        value: "true"

  # -- list of apis to be deployed
  # -- every api needs to define a name and image. Basepath is required when routes or ingress will be enabled. Beside that, they can overwrite the default-config by using the same keys.
  # -- be aware: when you change the image repositrory or the tag for an api, you have to provide both values for the changes to take effect
  apis:
    - name: party-catalog
      image: tmforum-party-catalog
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json

    - name: customer-bill-management
      image: tmforum-customer-bill-management
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF678_Customer_Bill/4.0.0/swagger/TMF678_Customer_Bill_Management_API_v4.0.0_swagger.json

    - name: customer-management
      image: tmforum-customer-management
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF629_Customer/4.0.0/swagger/TMF629_Customer_Management_API_v4.0.0_swagger.json

    - name: product-catalog
      image: tmforum-product-catalog
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json

    - name: product-inventory
      image: tmforum-product-inventory
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/4.0.0/swagger/TMF637_Product_Inventory_Management_API_v4.0.0_swagger.json

    - name: product-ordering-management
      image: tmforum-product-ordering-management
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF622_Product_Ordering/4.0.0/swagger/TMF622_Product_Ordering_Management_API_v4.0.0_swagger.json

    - name: resource-catalog
      image: tmforum-resource-catalog
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF634_Resource_Catalog/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json

    - name: resource-function-activation
      image: tmforum-resource-function-activation
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF664_Resource_Function_Activation/4.0.0/swagger/TMF664_Resource_Function_Activation_Management_API_v4.0.0_swagger.json

    - name: resource-inventory
      image: tmforum-resource-inventory
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF639_Resource_Inventory/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json

    - name: service-catalog
      image: tmforum-service-catalog
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json

    - name: service-inventory
      image: tmforum-service-inventory
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json

    - name: account
      image: tmforum-account
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF666_Account/4.0.0/swagger/TMF666_Account_Management_API_v4.0.0_swagger.json

    - name: agreement
      image: tmforum-agreement
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF651_Agreement/4.0.0/swagger/TMF651_Agreement_Management_API_v4.0.0_swagger.json

    - name: usage-management
      image: tmforum-usage-management
      basePath: /
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF635_Usage/4.0.0/swagger/TMF635_Usage_Management_API_v4.0.0_swagger.json
