trusted-issuers-list:

  # Image
  deployment:
    image:  
      tag: 0.2.0

  # Configure an Ingress or OpenShift Route
  ingress:
    til:
      enabled: false
    tir:
      enabled: false
  route:
    til:
      enabled: false
    tir:
      enabled: false
      
  # Database config
  database:
    persistence: true
    host: mysql-til
    name: til

    existingSecret:
      enabled: true
      name:  mysql-secret
      key: 

    username: root

  initData:
    initEnabled: true
    hook: post-install,post-upgrade
    issuers: 
      # allow ourself to issuer credentials
      - name: dome-marketplace
        issuer:
          did: "did:web:dome-marketplace.org"
          credentials:
            - validFor:
                from: "2023-07-21T17:32:28Z"
                to: "2040-07-21T17:32:28Z"
              credentialsType: "LegalPersonCredential"
            - validFor:
                from: "2023-07-21T17:32:28Z"
                to: "2040-07-21T17:32:28Z"
              credentialsType: "VerifiableCredential"
