dome-dss:
  app:
    internalServerPort: 8050
    config:
      sourceName: yaml
    certificate:
      existingSecret:
        # -- should an existing secret be used
        enabled: true
        # -- name of the secret
        name: dome-dss-secret
        # -- key to retrieve the token from
        key: certificate-password
    vault:
      provider: hashicorp
      host: dome-dss-vault-server
      scheme: http
      port: 8200
      token: defaultToken
      existingSecret:
        # -- should an existing secret be used
        enabled: true
        # -- name of the secret
        name: dome-dss-vault-unseal-secret
          # -- key to retrieve the token from
        key: root
      
  authServer:
    internalDomain: "http://dome-issuer-keycloak:8080/issuer-keycloak"
    externalDomain: "https://issuer.dome-marketplace-prd.org/issuer-keycloak"
    realm: CredentialIssuer