pdc-portal:
  deployment:
    image:
      repository: quay.io/i4trust/pdc-portal
      tag: 2.8.1
      pullPolicy: Always
    livenessProbe:
      initialDelaySeconds: 4
    readinessProbe:
      initialDelaySeconds: 5


  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-aws-prod
    className: nginx
    hosts:
      - host: onboarding-portal.dome-marketplace.org
        paths: 
          - "/"
    tls:
      - hosts: 
          - onboarding-portal.dome-marketplace.org
        secretName: onboarding-portal-tls-sec

  debug:
    enabled: true

  ccs:
    endpoint: "http://credentials-config-service-trust:8080/"
    id: "4972b082-c3db-414c-afb7-bf48f2fc42f6"
    credentials:
      - type: "VerifiableCredential"
        trustedParticipantsLists: [
          "https://tir.dsba.fiware.dev"
        ]
        trustedIssuersLists: [
          "http://trusted-issuers-list-trust:8080"
        ]

  config:
    title: "OnBoarding Portal"
    getLabel: "Get Participants"
    inputLabel: "Participant"

    external:
      host: https://onboarding-portal.dome-marketplace.org

    oidc:
      redirect_path: "/openid_connect1.0/return"
      acr: "urn:http://eidas.europa.eu/LoA/NotNotified/high"

    cb:
      endpoint: "https://kong-onboarding.dome-marketplace.org/orion/ngsi-ld/v1"
      endpoint_siop: "https://kong-onboarding.dome-marketplace.org/orion/ngsi-ld/v1"
    
    express:
      port: 7000

        
    # Configuration for SIOP flow
    siop:
      # SIOP flow enabled
      enabled: true
      # Base uri of the verifier
      verifier_uri: https://verifier-onboarding.dome-marketplace.org
      # DID of verifier
      did: "did:web:onboarding.dome-marketplace.org"
      # Client ID to be used
      client_id: 4972b082-c3db-414c-afb7-bf48f2fc42f6

    idp: []
