credentials-config-service:

  # Image
  deployment:
    image: 
      repository: quay.io/fiware/credentials-config-service
      tag: 1.0.1

  # Database config
  database:
    host: mysql-til
    name: ccs

    existingSecret:
      enabled: true
      name:  mysql-secret
      key: 

    username: root