apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: subscriptions-management-ingress
  namespace: billing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev2-issuer
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: manage.dome-marketplace-dev2.org
    http:
      paths:
      - path: /subscriptions
        pathType: Prefix
        backend:
          service:
            name: subscriptions-management-svc
            port:
              number: 8080
  tls:
  - hosts:
    - manage.dome-marketplace-dev2.org
    secretName: subscriptions-management-tls-secret