apiVersion: v1
kind: Service
metadata:
  name: subscriptions-management-svc
  namespace: billing
spec:
  selector:
    app.kubernetes.io/instance: subscriptions-management
    app.kubernetes.io/name: subscriptions-management
  ports:
    - name: http
      port: 8080
      targetPort: 8080