name: Deploy to the prd environment

on:
  push:
    branches:
      - 'main'

jobs:

  deploy:

    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v1

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG_DEV }}

      - name: Deploy prd applications
        run: |
          cd applications_prd
          # apply all apps in the apps folder
          find . -name '*.yaml'  -exec kubectl apply -f {} \;
          # label them for better filter machanism      
          find . -name '*.yaml'  -exec kubectl label deployed-by=fiware-gitops-ci --overwrite -f {} \;